[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ablator"
version = "0.0.1b2"
authors = [{ name = "Iordanis Fostiropoulos", email = "mail@iordanis.me" }]
readme = "README.md"
license = "LICENSE"
description = "Model Ablation Tool-Kit"
url = "https://ablator.org"
requires-python = ">=3.10,<3.13"

dependencies = [
    { name = "windows-curses", version = "^2.3.1", markers = "sys_platform == 'win32'" },
    "numpy~1.23.0",
    "pandas=1.5.3",
    "scikit-learn^1.3.0",
    "torch^2.0.1",
    "torchvision^0.15.2",
    "tqdm^4.65.0",
    "tensorboardX^2.6.1",
    "matplotlib^3.7.2",
    "omegaconf^2.3.0",
    "scipy^1.11.1",
    "setproctitle^1.3.2",
    # ray default as we need to use the state API
    # keeping it fixed as the API changes a lot between versions.
    "ray^2.6.1",
    # TODO when to migrate from "pydantic<2" to >2 https://github.com/ray-project/ray/issues/37019
    "pydantic=1.10.0",
    "pynvml^11.5.0",
    "optuna^3.2.0",
    "tabulate^0.9.0",
    "seaborn^0.12.2",
    "numpydoc^1.5.0",
    "paramiko^3.2.0",
    "gpustat^1.1" # must stay fixed because https://github.com/ray-project/ray/issues/35384
]

[project.optional-dependencies]
dev = [
    "mypy^1.4.1",
    "pytest^7.4.0",
    "black^23.7.0",
    "flake8^6.0.0",
    "pylint^2.17.5",
    "tensorboard<2.13.0",
    "mock^5.1.0",
    "types-tabulate^0.9.0.3",
    "types-paramiko^3.2.0.1",
    "docker^6.1.3",
    "pytest-xdist^3.3.1",
    "pytest-order^1.1.0",
    "pytest-rerunfailures^12.0",
    "pydoclint^0.1.4"
]
