name: Testing

on:
  push:
  pull_request:

jobs:
  pytest:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Generate SSH keys
        shell: bash
        run: |
          mkdir ~/.ssh
          ssh-keygen -t rsa -b 4096 -C "ablator@example.com" -f ~/.ssh/id_rsa -q -N ""
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
